create table if not exists public.bot_runtime_state (
  id text primary key default 'main',
  effective_mode text not null default 'always',
  source text not null default 'always',
  active boolean not null default true,
  title text not null default '',
  window text not null default '',
  detail text not null default '',
  timezone text not null default 'Asia/Ho_Chi_Minh',
  linked_count integer not null default 0,
  maintenance_mode boolean not null default false,
  maintenance_override boolean not null default false,
  fixed_schedule_enabled boolean not null default false,
  active_hours text not null default '',
  source_post_id text,
  source_post_title text,
  window_start timestamptz,
  window_end timestamptz,
  raw_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
