services:
  - type: worker
    name: prive-bot-worker
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python scheduler.py & python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0